import React from 'react';

export default function TermsAndPrivacy() {
  return (
    <div className="size-full">
      {/* Hero Section */}
      <section className="bg-background py-16 lg:py-20">
        <div className="mx-auto max-w-5xl px-6 space-y-6">
          <h1 className="font-bookmania text-4xl lg:text-6xl xl:text-7xl font-medium text-secondary tracking-tight text-center lg:text-left">
            Terms of Service & Privacy Policy
          </h1>
          <p className="text-lg lg:text-xl text-foreground/70 text-center lg:text-left">
            Last Updated: October 24, 2025
          </p>
        </div>
      </section>

      {/* Content Section */}
      <section className="bg-white-shade py-12 lg:py-20">
        <div className="mx-auto max-w-5xl px-6">
          <div className="space-y-16 lg:space-y-20">
            {/* TERMS OF SERVICE SECTION */}
            <div className="space-y-12 lg:space-y-16">
              <div className="text-center">
                <h1 className="font-bookmania text-5xl lg:text-6xl xl:text-7xl font-medium text-secondary tracking-tight mb-4">
                  Terms of Service
                </h1>
                <div className="w-24 h-1 bg-primary mx-auto"></div>
              </div>

              {/* Introduction */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  Terms of Service for Willow Path Services
                </h2>
                <div className="space-y-4">
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    Willow Path Co. (Willow Path or we) offers a web application designed to assist
                    individuals plan for their future and / or adjust to life moments (together, Willow Path
                    Services). Willow Path Services subject to these Willow Path Terms of Service (Willow Path
                    Terms).
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 font-semibold">
                    PLEASE READ THESE TERMS CAREFULLY. THESE TERMS INCLUDE IMPORTANT INFORMATION ABOUT YOUR
                    RELATIONSHIP WITH WILLOW PATH.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 font-semibold">
                    BY CLICKING A BUTTON OR CHECKING A BOX INDICATING ACCEPTANCE OF THESE TERMS OR OTHERWISE
                    AFFIRMATIVELY ACTIVATING OR USING THE WILLOW PATH SERVICES, YOU AFFIRM TO WILLOW PATH THAT
                    YOU UNDERSTAND AND AGREE TO THESE TERMS AND THE WILLOW PATH POLICY.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 font-semibold">
                    IF YOU DO NOT AGREE WITH THESE TERMS, YOU ARE NOT AUTHORIZED TO USE THE WILLOW PATH WEB
                    APPLICATION.
                  </p>
                </div>
              </div>

              {/* Section 1 - Key Definitions */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  1. Key Definitions
                </h2>
                <div className="space-y-4">
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    For your convenience, many of the capitalized terms that we use in these Willow Path Terms
                    are defined in this Section 1:
                  </p>
                  <div className="space-y-3">
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      <strong>Services Data</strong> means data that are generated by or derived from Users'
                      use of the Willow Path Services.
                    </p>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      <strong>Willow Path</strong> means businesses that offer products and services through
                      the Willow Path Services.
                    </p>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      <strong>Territory</strong> means the United States and its territories and possessions.
                    </p>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      <strong>Partner Content</strong> means technology and services provided by a third party
                      that interoperate with or otherwise support the Willow Path Services, such as security
                      and hosting service providers.
                    </p>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      <strong>User Data</strong> means data (including Personal Information, as defined in the
                      Willow Path Privacy Policy) in any form or medium that is transmitted to or through the
                      Willow Path Services or otherwise made available by a Customer and/or Users in
                      connection with the Willow Path Services but excluding Services Data.
                    </p>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      <strong>User or you</strong> means the person accessing and using the Willow Path
                      Services to help with caregiving responsibilities pursuant to Willow Path's contract
                      with a Customer.
                    </p>
                  </div>
                </div>
              </div>

              {/* Section 2 - How These Terms Apply */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  2. How These Willow Path Terms Apply
                </h2>
                <div className="space-y-4">
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    These Terms apply to the Willow Path Services. After you initially accept these Willow
                    Path Terms, you agree to the latest version of these Willow Path Terms when you access and
                    use the Willow Path Services. Certain Willow Path Services may require that you agree to
                    additional legal terms (Service Specific Terms). If any term of these Willow Path Terms
                    conflicts with any of the Service Specific Terms, then the Service Specific Terms control
                    with respect to the Willow Path Services to which they relate.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    Willow Path may have agreements with Willow Path Partners that contain terms applicable to
                    certain Willow Path Services or Users that are different from these Willow Path Terms. The
                    Willow Path Partner's agreement applies instead of these Willow Path Terms only when
                    expressly presented within the Willow Path Services and only to the extent of any conflict
                    or inconsistency.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    If you have a question about whether these Willow Path Terms apply to you, please contact{' '}
                    <a
                      href="mailto:support@willow-path.com"
                      className="text-primary hover:underline font-semibold">
                      support@willow-path.com
                    </a>
                    .
                  </p>
                </div>
              </div>

              {/* Section 3 - Accessing the Willow Path Services */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  3. Accessing the Willow Path Services
                </h2>
                <div className="space-y-4">
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      3.1 Access
                    </h3>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      Each User must provide their name and email to use the Willow Path Services.
                    </p>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 mt-3">
                      Willow Path may, in its sole discretion, suspend or terminate access to the Willow Path
                      Services if account information is inaccurate, out of date or incomplete (or if Willow
                      Path reasonably believes it is). If you believe that your account is no longer secure,
                      then you must immediately notify Willow Path at{' '}
                      <a
                        href="mailto:support@willow-path.com"
                        className="text-primary hover:underline font-semibold">
                        support@willow-path.com
                      </a>
                      .
                    </p>
                  </div>
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      3.2 Right to Use Willow Path Services
                    </h3>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      Subject to your compliance with these Willow Path Terms and applicable Service Specific
                      Terms, Willow Path and its licensors grant you the limited, non-exclusive,
                      non-transferable, non-sub-licensable and revocable right to access and use the Willow
                      Path Services in the Territory. Willow Path reserves all rights that are not expressly
                      granted in these Willow Path Terms. Willow Path makes the Willow Path Services available
                      in compliance with laws applicable to Willow Path and not necessarily in compliance with
                      laws applicable to your specific use of the Willow Path Services.
                    </p>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 mt-3">
                      The Willow Path Services may include software offered under an open-source license with
                      use requirements that supplement these Willow Path Terms. The Willow Path Services may
                      contain links to third-party websites and services for informational purposes. These
                      websites and services are not under Willow Path's control and Willow Path is not
                      responsible for their content.
                    </p>
                  </div>
                </div>
              </div>

              {/* Section 4 - Your Responsibilities */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  4. Your Responsibilities
                </h2>
                <div className="space-y-4">
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    You are solely responsible for:
                  </p>
                  <ul className="space-y-3 ml-6">
                    <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                      Compliance with these Willow Path Terms, including use of the Willow Path Services and
                      decisions and actions based on use of the Willow Path Services;
                    </li>
                    <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                      The lawfulness of User Data and Feedback (defined below);
                    </li>
                    <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                      The products and services made available by Willow Path Partners that you choose to use
                      and associated fees;
                    </li>
                    <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                      Your compliance with all applicable laws and regulations related to your use of the
                      Willow Path Services;
                    </li>
                    <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                      The security and use of your Access Credentials and all activities that occur through
                      those Account Credentials. (Please immediately notify Willow Path at{' '}
                      <a
                        href="mailto:support@willow-path.com"
                        className="text-primary hover:underline font-semibold">
                        support@willow-path.com
                      </a>{' '}
                      if you detect or suspect unauthorized activity.);
                    </li>
                    <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                      Use of reasonable and appropriate administrative, physical and technical safeguards to
                      protect against unauthorized access to or use of the Willow Path Services;
                    </li>
                    <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                      Reasonably cooperating with Willow Path when Willow Path believes your use of the Willow
                      Path Services violates law or any other part of these Willow Path Terms; and
                    </li>
                    <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                      The hardware and other equipment and internet connection through which you access and
                      use the Willow Path Services (including operation, maintenance and management) and all
                      access to and use of the Willow Path Services directly or indirectly through that
                      equipment and internet connection.
                    </li>
                  </ul>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 mt-6">
                    You are responsible for your use of the Willow Path Services, and you will defend and
                    indemnify Willow Path and its officers, directors, employees, consultants, licensors,
                    affiliates, subsidiaries and agents (together, the Willow Path Entities) from and against
                    every claim brought by a third party, and any related liability, damage, loss and expense,
                    including reasonable attorneys' fees and costs, arising out of or connected with: (a) your
                    unauthorized use or misuse of the Willow Path Services; (b) your violation of these Willow
                    Path Terms or applicable law; (c) any dispute or issue between you and any Willow Path
                    Partner or other third party; and (d) violation of any third-party intellectual property,
                    publicity, confidentiality, privacy or other legal property right. Willow Path reserves
                    the right, at our own expense, to assume the exclusive defense and control of any matter
                    subject to indemnification (without limiting your indemnification obligations with respect
                    to that matter) and you agree to cooperate with Willow Path's defense of those claims.
                  </p>
                </div>
              </div>

              {/* Section 5 - Conditions of Use */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  5. Conditions of Use
                </h2>
                <div className="space-y-4">
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      5.1 Acceptable Use
                    </h3>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      You understand and agree that you will not (and will use best efforts not to enable a
                      third party to):
                    </p>
                    <ul className="space-y-3 ml-6 mt-4">
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        copy, modify, frame, mirror or create derivative works or improvements of the Willow
                        Path Services;
                      </li>
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        rent, lease, lend, sell, sublicense, assign, distribute, publish, transfer or
                        otherwise make available any of the Willow Path Services to any third party, including
                        on or in connection with the internet or any time-sharing, service bureau, software as
                        a service, cloud or other technology or service;
                      </li>
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        reverse engineer, disassemble, decompile, decode, adapt or otherwise attempt to derive
                        or gain access to the source code of the Willow Path Services, in whole or in part;
                      </li>
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        bypass or breach any security device or protection used for the Willow Path Services
                        or access or use the Willow Path Services other than with your own valid Access
                        Credentials;
                      </li>
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        input, upload, transmit or otherwise provide to or through the Willow Path Services
                        any User Data or other information or materials that are unlawful or injurious to
                        Willow Path or any third party or contain, transmit or activate any virus, worm,
                        malware or other malicious computer code;
                      </li>
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        damage, destroy, disrupt, disable, impair or otherwise impede or harm in any manner
                        the Willow Path Services or Willow Path's provision of the Willow Path Services, in
                        whole or in part;
                      </li>
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        remove, delete, alter or obscure any copyright, trademark, patent or other
                        intellectual property or proprietary rights notice from any of the Willow Path
                        Services;
                      </li>
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        access or use the Willow Path Services in any manner or for any purpose that
                        infringes, misappropriates or otherwise violates any right of any third party
                        (including by any unauthorized access to, misappropriation, use, alteration,
                        destruction or disclosure of the data of any other customer) or that violates any
                        applicable law;
                      </li>
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        access or use the Willow Path Services for purposes of competitive analysis of the
                        Willow Path Services, the development, provision or use of a competing product or
                        service or any other purpose that is to Willow Path's detriment or commercial
                        disadvantage; or
                      </li>
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        otherwise access or use the Willow Path Services beyond the scope of the authorization
                        expressly granted under these Willow Path Terms.
                      </li>
                    </ul>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 mt-4">
                      The Willow Path Services are not targeted for use by minors.
                    </p>
                  </div>
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      5.2 Disclosure of User Data
                    </h3>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      Customer and Users agree that Willow Path may disclose User Data if (i) Willow Path
                      believes that disclosure is reasonably necessary to comply with any law or a request
                      from a government regulator or communications service provider that Willow Path believes
                      in good faith is lawful, (ii) to enforce our agreements and policies, (iii) to protect
                      the security or integrity of the Willow Path Services, (iv) to protect ourselves, our
                      other customers or the public from harm or illegal activities, or (v) to respond to an
                      emergency that Willow Path believes in good faith requires us to disclose User Data.
                    </p>
                  </div>
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      5.3 Monitoring
                    </h3>
                    <div className="space-y-4">
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                        Willow Path does not control how Users use the Willow Path Services or data that Users
                        submit to or transmit through the Willow Path Services. You understand that, when
                        using the Willow Path Services, you may be exposed to content from a variety of
                        sources and acknowledge that the content may be inaccurate, offensive, indecent or
                        objectionable.
                      </p>
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                        You are solely responsible for your User Data and the consequences of providing User
                        Data via the Willow Path Services. Willow Path disclaims all liability that arises in
                        connection with User Data. You hereby waive any legal or equitable right or remedy you
                        may have against Willow Path with respect to User Data.
                      </p>
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                        You understand that Willow Path may, at any time and without prior notice, screen,
                        remove, edit or block any User Data that in Willow Path's sole judgment violates these
                        Willow Path Terms or is otherwise objectionable. You acknowledge and agree that Willow
                        Path reserves the right to, and may from time to time, monitor data transmitted or
                        received through the Willow Path Services for operational and other lawful purposes.
                        If at any time Willow Path chooses to monitor the Willow Path Services, Willow Path
                        assumes no additional responsibility or liability to you or any third party.
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Section 6 - Intellectual Property Rights */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  6. Intellectual Property Rights
                </h2>
                <div className="space-y-4">
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      6.1 Ownership of User Data
                    </h3>
                    <div className="space-y-4">
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                        You are and will remain the sole and exclusive owner of all right, title and interest
                        in and to your User Data, including all intellectual property rights relating thereto.
                        You hereby irrevocably grant to Willow Path all rights and permissions in or relating
                        to User Data that Willow Path determines necessary or useful to perform the Willow
                        Path Services, enforce these Willow Path Terms or otherwise exercise Willow Path's
                        rights and perform Willow Path's obligations. By providing your User Data to or
                        through the Willow Path Services to other users of the Willow Path Services, you grant
                        those users a non-exclusive license to access and use your User Data as permitted by
                        these Willow Path Terms and the functionality of the Willow Path Services.
                      </p>
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                        You expressly acknowledge that User Data excludes Services Data. In furtherance of the
                        foregoing, you hereby unconditionally and irrevocably grant to Willow Path all right,
                        title and interest you may have in and to Services Data.
                      </p>
                    </div>
                  </div>
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      6.2 Ownership of Willow Path Services
                    </h3>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      The Willow Path Services are owned and operated by Willow Path. The visual interfaces,
                      graphics, design, compilation, information, data, computer code (including source code
                      or object code), products, software, services, and all other elements of the Willow Path
                      Services provided by Willow Path (Willow Path Content) are protected by intellectual
                      property and other laws. All Willow Path Content included in the Willow Path Services
                      are the property of Willow Path or its third-party licensors. Except as expressly
                      authorized by these Willow Path Terms or otherwise by Willow Path, you may not use the
                      Willow Path Content. Willow Path reserves all rights to the Willow Path Content not
                      granted expressly in these Willow Path Terms.
                    </p>
                  </div>
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      6.3 Ownership of Partner Content
                    </h3>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      With respect to content provided by Willow Path Partners (Partner Content), the Willow
                      Path Partner and/or its licensors own all right, title and interest, including all
                      intellectual property rights, in and to Partner Content. You have no right, license or
                      authorization with respect to Partner Content except as expressly set forth in the
                      applicable third-party license. All other rights in and to the Partner Content are
                      expressly reserved by the applicable third-party licensor.
                    </p>
                  </div>
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      6.4 Feedback
                    </h3>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      If you choose to provide input and suggestions regarding problems with or proposed
                      modifications or improvements to the Willow Path Services (Feedback), then you grant
                      Willow Path and its transferees a fully paid, royalty-free, perpetual, irrevocable,
                      worldwide, non-exclusive and fully sub-licensable right and license to use, reproduce,
                      perform, display, distribute, adapt, modify, re-format, create derivative works of and
                      otherwise exploit in any manner all Feedback. You also acknowledge and agree that Willow
                      Path may publish your Feedback on its website and attribute that Feedback to you.
                    </p>
                  </div>
                </div>
              </div>

              {/* Section 7 - Changes to Willow Path Services and Terms */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  7. Changes to Willow Path Services and These Willow Path Terms
                </h2>
                <div className="space-y-4">
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      7.1 Updates
                    </h3>
                    <div className="space-y-4">
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                        We are always looking to innovate and make the Willow Path Services better. As a
                        result, Willow Path may from time to time update the Willow Path Services, including
                        enhancements, modifications, upgrades and other changes to the existing features and
                        operability of the Willow Path Services (collectively, Updates). These Updates may
                        occur for various reasons, such as adding or removing functionality, fixing bugs, and
                        addressing issues relating to security or performance. Whenever possible, Willow Path
                        will provide you with reasonable, advance notice (which may include notice by way of
                        posting in the Willow Path Services) of material Updates to enable you to prepare for
                        the Updates. You acknowledge and agree that Updates made to comply with applicable law
                        may not allow Willow Path to provide advance notice of Updates.
                      </p>
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                        You acknowledge, understand and agree that the Willow Path Services and Updates may
                        (i) cause your mobile telephone, computer and/or network equipment to automatically
                        communicate with Willow Path's (or one of its third-party service provider's) servers
                        to deliver the functionality described in these Willow Path Terms and to record User
                        Data and Services Data, (ii) affect preferences or data stored in your device, and
                        (iii) collect personal information and other information, as described in the Willow
                        Path Privacy Policy.
                      </p>
                    </div>
                  </div>
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      7.2 Other Modifications to Willow Path Services
                    </h3>
                    <div className="space-y-4">
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                        Willow Path reserves the right to modify, limit or discontinue the Willow Path
                        Services at any time (including by limiting or discontinuing certain features of the
                        Willow Path Services), temporarily or permanently, without notice to you.
                      </p>
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                        Willow Path may elect to deprecate certain functionality or features within the Willow
                        Path Services upon notice posted through the Willow Path Services. Whenever possible,
                        Willow Path will provide at least ninety (90) days' advance notice of deprecation of
                        any material function (and any related support) within the Willow Path Services. You
                        acknowledge and agree that deprecations made to comply with applicable law may not
                        allow Willow Path to provide advance notice.
                      </p>
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                        To the fullest extent permitted by law, Willow Path will have no liability to you or
                        any third party for any change to the Willow Path Services or any suspension or
                        termination of your access to or use of the Willow Path Services made in accordance
                        with these Willow Path Terms.
                      </p>
                    </div>
                  </div>
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      7.3 Changes to Terms
                    </h3>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      You acknowledge and agree that Willow Path has the right to modify these Willow Path
                      Terms from time to time to reflect changes to the Willow Path Services, industry
                      requirements or applicable law. Willow Path will notify you at least thirty (30)
                      business days in advance of the material modifications to these Willow Path Terms.
                      Willow Path will send notifications of material modifications by email using the email
                      address(es) associated with your Account Credentials and/or through a notice posted in
                      the Willow Path Services. You agree that Willow Path may notify you by posting a notice
                      in the Willow Path Services for non-material changes to the Willow Path Services. You
                      acknowledge and agree that changes to applicable law may prevent Willow Path from
                      providing advance notification. Continued use of the Willow Path Services after the end
                      of the notice period specified in the notification is deemed conclusive acceptance of
                      these Willow Path Terms as modified.
                    </p>
                  </div>
                </div>
              </div>

              {/* Section 8 - Availability of Willow Path Services */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  8. Availability of Willow Path Services
                </h2>
                <div className="space-y-4">
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    You acknowledge that the Willow Path Services are not error-free or 100% reliable or
                    available. Proper functioning of the Willow Path Services relies and is dependent on,
                    among other things, broadband internet access used to transmit data through the Wi-Fi
                    network and the wireless device used. The Willow Path Services may be interrupted,
                    delayed, refused or otherwise limited for a variety of reasons, such as insufficient
                    coverage, power outages, termination of service, environmental conditions, interference,
                    non-payment of applicable fees, system capacity, repairs, relocations and priority access
                    by emergency responders in the event of a disaster or emergency (Service Interruptions).
                    You understand that Service Interruptions may make the Willow Path Services unreliable or
                    unavailable for the duration of the Service Interruption. Although Willow Path uses
                    commercially reasonable efforts to notify you of Service Interruptions, Willow Path cannot
                    and does not guarantee that you will receive these notifications.{' '}
                    <strong>
                      YOU AGREE THAT YOU WILL NOT RELY ON THE WILLOW PATH SERVICES FOR ANY LIFE SAFETY OR
                      CRITICAL PURPOSES.
                    </strong>{' '}
                    You agree that you will not be entitled to any refund or rebate for service interruptions
                    or suspensions. Willow Path does not offer any specific uptime guarantee for the Willow
                    Path Services.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    The Willow Path Services are available only in the U.S. Territory. Willow Path makes no
                    representation that the Willow Path Services, or any feature or part thereof, are
                    appropriate or available for use in any other location. To the extent you choose to access
                    and use the Willow Path Services outside the Territory, you do so at your own initiative
                    and are responsible for compliance with applicable laws.
                  </p>
                </div>
              </div>

              {/* Section 9 - Disclaimers; No Warranties */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  9. Disclaimers; No Warranties
                </h2>
                <div className="space-y-4">
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      9.1 Waiver and Disclaimers
                    </h3>
                    <div className="space-y-4">
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 font-semibold">
                        THE WILLOW PATH SERVICES AND OTHER CONTENT AVAILABLE THROUGH THE WILLOW PATH SERVICES
                        ARE PROVIDED "AS IS" AND ON AN "AS AVAILABLE" BASIS.
                      </p>
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 font-semibold">
                        THE WILLOW PATH ENTITIES DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
                        IMPLIED, RELATING TO THE WILLOW PATH SERVICES AND ALL MATERIALS AND CONTENT AVAILABLE
                        THROUGH THE WILLOW PATH SERVICES, INCLUDING: (A) ANY IMPLIED WARRANTY OF
                        MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT OR
                        NON-INFRINGEMENT; AND (B) ANY WARRANTY ARISING OUT OF COURSE OF DEALING, USAGE OR
                        TRADE. WILLOW PATH DOES NOT WARRANT THAT THE WILLOW PATH SERVICES OR CONTENT OFFERED
                        THROUGH THE WILLOW PATH SERVICES WILL BE UNINTERRUPTED, SECURE OR FREE OF ERRORS,
                        VIRUSES OR OTHER HARMFUL COMPONENTS OR THAT WILLOW PATH WILL CORRECT ERRORS.
                      </p>
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 font-semibold">
                        WILLOW PATH MAKES NO WARRANTY, REPRESENTATION OR CONDITION THAT THE WILLOW PATH
                        SERVICES WILL MEET YOUR REQUIREMENTS OR WILL BE ACCURATE OR RELIABLE OR THAT WILLOW
                        PATH WILL CONTINUE TO OFFER THE WILLOW PATH SERVICES IN WHOLE OR IN PART.
                      </p>
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 font-semibold">
                        NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM THE WILLOW
                        PATH ENTITIES OR ANY MATERIALS OR CONTENT AVAILABLE THROUGH THE WILLOW PATH SERVICES,
                        WILL CREATE ANY WARRANTY THAT IS NOT EXPRESSLY STATED IN THESE WILLOW PATH TERMS.
                        WILLOW PATH IS NOT RESPONSIBLE FOR ANY DAMAGE THAT MAY RESULT FROM THE WILLOW PATH
                        SERVICES AND YOUR DEALING WITH ANY OTHER USER OR WILLOW PATH PARTNERS. YOU UNDERSTAND
                        AND AGREE THAT YOU USE THE WILLOW PATH SERVICES AT YOUR OWN DISCRETION AND RISK, AND
                        THAT WE ARE NOT RESPONSIBLE FOR ANY DAMAGE TO YOUR PROPERTY (INCLUDING YOUR COMPUTER
                        SYSTEM OR MOBILE DEVICE USED IN CONNECTION WITH THE WILLOW PATH SERVICES) OR ANY LOSS
                        OF DATA.
                      </p>
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                        Willow Path is not responsible for loss or damages arising from unauthorized use of
                        Account Credentials unless such loss or damage arises directly from Willow Path's
                        gross negligence or willful misconduct.
                      </p>
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 font-semibold">
                        THE LIMITATIONS, EXCLUSIONS AND DISCLAIMERS IN THIS SECTION APPLY TO THE MAXIMUM
                        EXTENT PERMITTED BY LAW. Willow Path does not disclaim any warranty or other right
                        that Willow Path is prohibited from disclaiming under applicable law. TO THE EXTENT
                        ANY OF THE LIMITATIONS, EXCLUSIONS AND DISCLAIMERS CONFLICTS WITH APPLICABLE LAW, THE
                        SCOPE AND DURATION OF THE WARRANTIES APPLICABLE TO THE WILLOW PATH SERVICES WILL BE
                        THE MINIMUM PERMITTED UNDER THAT LAW.
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Section 10 - Limitation of Liability */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  10. Limitation of Liability
                </h2>
                <div className="space-y-4">
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 font-semibold">
                    THE LIMITATIONS AND EXCLUSIONS IN THIS SECTION APPLY TO THE MAXIMUM EXTENT PERMITTED BY
                    LAW. WILLOW PATH DOES NOT LIMIT OR EXCLUDE ANY LIABILITY THAT IS PROHIBITED FROM BEING
                    LIMITED OR EXCLUDED UNDER APPLICABLE LAW. TO THE EXTENT ANY LIMITATION OR EXCLUSION
                    CONFLICTS WITH APPLICABLE LAW, WILLOW PATH'S LIABILITY WILL BE THE MINIMUM PERMITTED UNDER
                    THAT LAW.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 font-semibold">
                    IN NO EVENT WILL THE WILLOW PATH ENTITIES BE LIABLE TO YOU OR THIRD PARTY ACCESSING OR
                    USING THE WILLOW PATH SERVICES PURSUANT TO YOUR ACCOUNT FOR ANY INDIRECT, INCIDENTAL,
                    SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES (INCLUDING DAMAGES FOR LOSS OF PROFITS,
                    GOODWILL, OR ANY OTHER INTANGIBLE LOSS) ARISING OUT OF OR RELATING TO ACCESS TO OR USE OF,
                    OR INABILITY TO ACCESS OR USE, THE WILLOW PATH SERVICES OR ANY CONTENT ON THE WILLOW PATH
                    SERVICES, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STATUTE, OR
                    ANY OTHER LEGAL THEORY, AND WHETHER OR NOT ANY WILLOW PATH ENTITY HAS BEEN INFORMED OF THE
                    POSSIBILITY OF DAMAGE. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, Willow Path is
                    not responsible for loss or damages arising from unauthorized use of Account Credentials
                    unless such loss or damage arises directly from Willow Path's gross negligence or willful
                    misconduct.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 font-semibold">
                    TO THE FULLEST EXTENT PERMITTED BY LAW, THE AGGREGATE LIABILITY OF THE WILLOW PATH
                    ENTITIES TO YOU OR ANY THIRD PARTY FOR ACCESSING OR USING THE WILLOW PATH SERVICES
                    PURSUANT TO YOUR ACCOUNT WITH WILLOW PATH, FOR CLAIMS ARISING OUT OF OR RELATED TO THE USE
                    OF OR ANY INABILITY TO USE THE WILLOW PATH SERVICES OR OTHERWISE UNDER THESE WILLOW PATH
                    TERMS, WHETHER IN CONTRACT, TORT OR OTHERWISE, IS LIMITED TO THE GREATER OF: (A) THE
                    AMOUNT YOU PAID TO WILLOW PATH FOR ACCESS TO AND USE OF THE WILLOW PATH SERVICES IN THE 12
                    MONTHS PRIOR TO THE EVENT OR CIRCUMSTANCE GIVING RISE TO THE CLAIM (BUT NOT INCLUDING THE
                    PURCHASE PRICE FOR ANY WILLOW PATH PRODUCTS) AND (B) $1,000.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 font-semibold">
                    EACH PROVISION OF THESE WILLOW PATH TERMS THAT PROVIDES FOR A LIMITATION OF LIABILITY,
                    DISCLAIMER OF WARRANTIES, OR EXCLUSION OF DAMAGES IS INTENDED TO AND DOES ALLOCATE THE
                    RISKS BETWEEN WILLOW PATH AND CUSTOMER AND USERS UNDER THESE WILLOW PATH TERMS. THIS
                    ALLOCATION IS AN ESSENTIAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN WILLOW PATH AND
                    YOU. EACH OF THESE PROVISIONS IS SEVERABLE AND INDEPENDENT OF ALL OTHER PROVISIONS OF
                    THESE WILLOW PATH TERMS. THE LIMITATIONS IN THIS SECTION 10 WILL APPLY EVEN IF ANY LIMITED
                    REMEDY FAILS OF ITS ESSENTIAL PURPOSE.
                  </p>
                </div>
              </div>

              {/* Section 11 - Dispute Resolution */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  11. Dispute Resolution
                </h2>
                <div className="space-y-4">
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      11.1 Governing Law
                    </h3>
                    <div className="space-y-4">
                      <div>
                        <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                          These Willow Path Terms and your use of the Willow Path Services are governed by the
                          laws of the State of Delaware, without regard to its choice of law provisions. You
                          and Willow Path submit to the personal and exclusive jurisdiction of the state
                          courts and federal courts located within Delaware for resolution of any lawsuit or
                          court proceeding permitted under these Willow Path Terms.
                        </p>
                        <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                          [Note: Insert applicable state jurisdiction here if desired.]
                        </p>
                      </div>
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 font-semibold">
                        TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, YOU AGREE THAT ANY CAUSE OF ACTION
                        ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE
                        CAUSE OF ACTION ACCRUES; OTHERWISE, THE CAUSE OF ACTION IS PERMANENTLY BARRED.
                      </p>
                    </div>
                  </div>
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      11.2 No Class Actions
                    </h3>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 font-semibold">
                      YOU AND WILLOW PATH AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR
                      ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR
                      REPRESENTATIVE PROCEEDING.
                    </p>
                  </div>
                </div>
              </div>

              {/* Section 12 - General Terms */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  12. General Terms
                </h2>
                <div className="space-y-4">
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      12.1 Electronic Communications
                    </h3>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      The communications between you and Willow Path may use electronic means. Except as
                      prohibited by applicable law, you (a) consent to receive communications from Willow Path
                      in an electronic form; and (b) agree that all terms and conditions, agreements, notices,
                      disclosures, and other communications that Willow Path electronically provides to you
                      satisfy any legal requirement that such communications would satisfy if it were to be in
                      writing.
                    </p>
                  </div>
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      12.2 US Government Rights
                    </h3>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      The Willow Path Services are a "commercial item" as defined at 48 C.F.R. 2.101,
                      consisting of "commercial computer software" and "commercial computer software
                      documentation" as such terms are used in 48 C.F.R. 12.212. Accordingly, if Customer is
                      an agency of the US Government or any contractor therefor, Customer only receives those
                      rights with respect to the Willow Path Services as are granted to all other customers
                      and users under license, in accordance with (i) 48 C.F.R. §227.7201 through 48 C.F.R.
                      §227.7204, with respect to the Department of Defense and their contractors, or (ii) 48
                      C.F.R. §12.212, with respect to all other US Government licensees and their contractors.
                    </p>
                  </div>
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      12.3 Force Majeure
                    </h3>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      No failure, delay or default in performance of any obligation of a party shall
                      constitute an event of default or breach of these Willow Path Terms to the extent that
                      such failure to perform, delay or default arises out of a cause, existing or future,
                      that is beyond the control and without negligence of such party, including action or
                      inaction of governmental, civil or military authority; fire; strike, lockout or other
                      labor dispute; flood, terrorist act; war; riot; theft; earthquake and other natural
                      disaster. The party affected by such cause shall take all reasonable actions to minimize
                      the consequences of any such cause.
                    </p>
                  </div>
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      12.4 Notice to California Residents
                    </h3>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      If you are a California resident, under California Civil Code Section 1789.3, you may
                      contact the Complaint Assistance Unit of the Division of Consumer Services of the
                      California Department of Consumer Affairs in writing at 1625 N. Market Blvd., Suite
                      S-202, Sacramento, California 95834, or by telephone at (800) 952-5210 in order to
                      resolve a complaint regarding the Willow Path Services or to receive further information
                      regarding use of the Willow Path Services.
                    </p>
                  </div>
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      12.5 Other General Terms
                    </h3>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      These Terms, together with the Willow Path Privacy Policy and any other agreements
                      expressly incorporated by reference into these Willow Path Terms, are the entire and
                      exclusive understanding and agreement between you and Willow Path regarding your use of
                      the Willow Path Services. You may not assign or transfer these Willow Path Terms or your
                      rights under these Willow Path Terms, in whole or in part, by operation of law or
                      otherwise, without our prior written consent. Willow Path may assign these Willow Path
                      Terms at any time without notice or consent. The failure to require performance of any
                      provision will not affect our right to require performance at any other time after that,
                      nor will a waiver by us of any breach or default of these Willow Path Terms, or any
                      provision of these Willow Path Terms, be a waiver of any subsequent breach or default or
                      a waiver of the provision itself. If any part of these Willow Path Terms is held to be
                      invalid or unenforceable, the unenforceable part will be given effect to the greatest
                      extent possible, and the remaining parts will remain in full force and effect. You and
                      Willow Path are independent contractors in the performance of every part of these Willow
                      Path Terms. Nothing in these Willow Path Terms is intended to create or shall be
                      construed as creating an employer-employee relationship or a partnership, agency, joint
                      venture, or franchise. You and Willow Path are and will be solely responsible for
                      your/its respective employees and agents and respective labor costs and expenses arising
                      in connection with those employees and agents. Use of section headers in these Willow
                      Path Terms is for convenience only and will not have any impact on the interpretation of
                      any provision.
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* PRIVACY POLICY SECTION */}
            <div className="space-y-12 lg:space-y-16">
              <div className="text-center">
                <h1 className="font-bookmania text-5xl lg:text-6xl xl:text-7xl font-medium text-secondary tracking-tight mb-4">
                  Privacy Policy
                </h1>
                <div className="w-24 h-1 bg-primary mx-auto"></div>
              </div>

              {/* Privacy Introduction */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  Willow Path Co. Privacy Policy
                </h2>
                <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                  Willow Path Co. and its subsidiaries and affiliates (collectively, "WILLOW PATH," "we," or
                  "us") offer web and mobile services and related offerings that facilitate caregiving
                  planning by employees and care team members for care recipients ("WILLOW PATH Services").
                  This Privacy Policy explains the personal information we process, how we use it, and your
                  rights.
                </p>
                <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                  This Privacy Policy also serves as our Notice at Collection for purposes of U.S. Privacy
                  Laws.
                </p>
              </div>

              {/* Section 1 - Key Definitions */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  1. Key Definitions
                </h2>
                <div className="space-y-4">
                  <div className="space-y-3">
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      <strong>Business Purposes</strong> means performing the WILLOW PATH Services; managing
                      and processing interactions and transactions with Users; securing and debugging;
                      advertising and marketing (including email marketing communications and survey follow-up
                      outreach); quality assurance; research and development; and other purposes as defined by
                      U.S. Privacy Laws.
                    </p>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      <strong>User (or "you")</strong> means the person accessing and using WILLOW PATH
                      Services.
                    </p>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      <strong>Personal Information</strong> means information that identifies or can
                      reasonably be used to identify an individual.
                    </p>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      <strong>Processing</strong> means any operation performed on personal information, such
                      as collecting, storing, combining, or sharing.
                    </p>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      <strong>Sale or Selling</strong> means selling, renting, releasing, disclosing,
                      disseminating, making available, or otherwise communicating a User's personal
                      information for monetary or other valuable consideration.
                    </p>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      <strong>Share or Sharing</strong> means sharing personal information for cross-context
                      behavioral advertising.
                    </p>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      <strong>WILLOW PATH Partners</strong> means businesses that offer products and services
                      through WILLOW PATH Services.
                    </p>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      <strong>Vendors</strong> means service providers that process personal information on
                      behalf of WILLOW PATH.
                    </p>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      <strong>U.S. Privacy Laws</strong> means the California Consumer Privacy Act (as amended
                      by the CPRA), Colorado Privacy Act, Connecticut Data Privacy Act, Utah Consumer Privacy
                      Act, and Virginia Consumer Data Protection Act, as amended or replaced from time to
                      time.
                    </p>
                  </div>
                </div>
              </div>

              {/* Section II - When and Where This Privacy Policy Applies */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  2. When and Where This Privacy Policy Applies
                </h2>
                <div className="space-y-4">
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    This Privacy Policy covers the twelve (12) months prior to the Last Updated date and is
                    updated at least once per year. If our processing materially changes between updates, we
                    will provide a supplemental notice when or before the changes apply.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    This Privacy Policy applies to individuals who reside in the United States.
                  </p>
                </div>
              </div>

              {/* Email Collection Section */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  3. Collection of Personal Information
                </h2>
                <div className="space-y-4">
                  <div>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      WILLOW PATH collects personal information:
                    </p>
                    <ul className="space-y-2 ml-6 mt-3">
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        Directly from you (e.g., account registration, surveys, email subscriptions)
                      </li>
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        From your devices (e.g., browser information, IP addresses)
                      </li>
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        From our affiliates and service providers
                      </li>
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        From public sources
                      </li>
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        From other businesses or individuals
                      </li>
                    </ul>
                  </div>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    We generally process personal information to provide and improve WILLOW PATH Services,
                    operate our business, and for the Business Purposes described above.
                  </p>
                  <div>
                    <h3 className="text-xl lg:text-2xl xl:text-3xl font-semibold text-secondary mb-3">
                      Email Collection for Marketing and Survey Follow-Up
                    </h3>
                    <div className="space-y-4">
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                        Beginning in 2025, we collect email addresses from Users for two primary purposes:
                      </p>
                      <ol className="space-y-3 ml-6">
                        <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                          <strong>1. Marketing Communications</strong> – With your consent, we use your email
                          to send newsletters, promotional offers, service updates, and other marketing
                          content related to WILLOW PATH Services.
                        </li>
                        <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                          <strong>2. Survey & Interaction Follow-Up</strong> – When you complete a survey or
                          interact with our platform, we may collect your email address to follow up with
                          clarifying questions, request feedback, or provide additional information related to
                          your responses or experience.
                        </li>
                      </ol>
                      <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                        You may opt out of marketing emails at any time by clicking "unsubscribe" in any email
                        or by contacting us at{' '}
                        <a
                          href="mailto:support@willow-path.com"
                          className="text-primary hover:underline font-semibold">
                          support@willow-path.com
                        </a>
                        .
                      </p>
                    </div>
                  </div>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 mt-4">
                    Opting out of marketing communications does not affect our ability to contact you for
                    essential follow-up questions related to surveys or direct interactions with WILLOW PATH
                    Services, provided such follow-up is reasonably necessary to complete or support the
                    interaction.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 mt-4">
                    We may use trusted Vendors (e.g., email campaign providers, survey management providers)
                    to help deliver both marketing and follow-up communications, subject to strict
                    confidentiality and data protection obligations.
                  </p>
                </div>
              </div>

              {/* Section 4 - Disclosure of Personal Information */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  4. Disclosure of Personal Information
                </h2>
                <div className="space-y-4">
                  <div>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                      WILLOW PATH discloses personal information:
                    </p>
                    <ul className="space-y-2 ml-6 mt-3">
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        To Vendors providing services on our behalf (e.g., data analytics, cloud storage,
                        survey and email marketing providers)
                      </li>
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        To WILLOW PATH Partners
                      </li>
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        To government entities or law enforcement, when required
                      </li>
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        In connection with corporate transactions (e.g., mergers, acquisitions)
                      </li>
                      <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                        With your consent or at your direction
                      </li>
                    </ul>
                    <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 mt-4">
                      We do not sell your personal information for monetary value. However, we may share
                      personal information as described above for cross-context behavioral advertising.
                    </p>
                  </div>
                </div>
              </div>

              {/* Section 5 - Retention */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  5. Retention
                </h2>
                <div className="space-y-4">
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    We retain personal information for as long as reasonably necessary to carry out the
                    purposes described in this Privacy Policy, including legal compliance, dispute resolution,
                    and enforcement of agreements.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    Email addresses collected for marketing are retained until you opt out, request deletion,
                    or until we no longer need them for marketing purposes.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    Email addresses collected for survey follow-up are retained only as long as necessary to
                    complete the follow-up process or for related business purposes, unless you request
                    deletion sooner.
                  </p>
                </div>
              </div>

              {/* Section 6 - Your Privacy Rights */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  6. Your Privacy Rights
                </h2>
                <div className="space-y-4">
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    Subject to verification, you may exercise the following rights:
                  </p>
                  <ul className="space-y-3 ml-6">
                    <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                      <strong>Right to Know/Access</strong> – Request information about the categories and
                      specific pieces of personal information collected, disclosed, or shared.
                    </li>
                    <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                      <strong>Right to Delete</strong> – Request deletion of your personal information,
                      subject to legal exceptions.
                    </li>
                    <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                      <strong>Right to Correct</strong> – Request correction of inaccurate personal
                      information.
                    </li>
                    <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                      <strong>Do Not Sell/Share/Target</strong> – Opt out of the sale, sharing, or use of your
                      personal information for targeted advertising, including email addresses used for direct
                      marketing.
                    </li>
                    <li className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 list-disc">
                      <strong>Right to Limit Sensitive Personal Information Processing</strong> – Request
                      limitations on the use of sensitive personal information.
                    </li>
                  </ul>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 mt-4">
                    You may exercise your rights by emailing{' '}
                    <a
                      href="mailto:support@willow-path.com"
                      className="text-primary hover:underline font-semibold">
                      support@willow-path.com
                    </a>
                    .
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    We will verify your identity before fulfilling certain requests. You may also designate an
                    authorized agent, subject to additional verification requirements.
                  </p>
                </div>
              </div>

              {/* Section 7 - Notice of Financial Incentives */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  7. Notice of Financial Incentives
                </h2>
                <div className="space-y-4">
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    We may offer discounts, promotional offers, or other incentives to Users who subscribe to
                    our marketing communications. Participation is voluntary, and you may withdraw at any
                    time.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    We value the personal information collected for such programs based on the benefits
                    provided (e.g., discounts) and the type of information collected (e.g., email address).
                  </p>
                </div>
              </div>

              {/* Section 8 - Non-Discrimination */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  8. Non-Discrimination
                </h2>
                <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                  We will not discriminate against you for exercising your privacy rights. However, we may
                  offer different prices, rates, or levels of service if reasonably related to the value of
                  personal information provided.
                </p>
              </div>

              {/* Section 9 - Shine the Light Law */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  9. Shine the Light Law (California)
                </h2>
                <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                  California residents may request information about our disclosure of personal information to
                  third parties for their direct marketing purposes by emailing{' '}
                  <a
                    href="mailto:support@willow-path.com"
                    className="text-primary hover:underline font-semibold">
                    support@willow-path.com
                  </a>{' '}
                  with the subject line "Shine the Light Request."
                </p>
              </div>

              {/* Section 10 - Contact Us */}
              <div className="space-y-4 lg:space-y-6">
                <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                  10. Contact Us
                </h2>
                <div className="space-y-4">
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    If you have questions or concerns about this Privacy Policy or our practices, contact us:
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    Email:{' '}
                    <a
                      href="mailto:support@willow-path.com"
                      className="text-primary hover:underline font-semibold">
                      support@willow-path.com
                    </a>
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    Willow Path Co. does not knowingly collect or process personal information from children
                    under 13. If we learn that we have done so, we will delete the information promptly.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    We implement reasonable administrative, technical, and physical safeguards designed to
                    protect personal information from unauthorized access, disclosure, alteration, or
                    destruction.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    In the event of a data breach, Willow Path Co. will notify affected individuals in
                    accordance with applicable law.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    If you are dissatisfied with our response to a privacy rights request, you may appeal by
                    contacting{' '}
                    <a
                      href="mailto:support@willow-path.com"
                      className="text-primary hover:underline font-semibold">
                      support@willow-path.com
                    </a>
                    .
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    This Privacy Policy is effective as of October 24, 2025, and replaces prior versions.
                  </p>
                </div>
              </div>
            </div>

            {/* ADDITIONAL NOTES SECTION */}
            <div className="space-y-12 lg:space-y-16">
              <div className="text-center">
                <h1 className="font-bookmania text-5xl lg:text-6xl xl:text-7xl font-medium text-secondary tracking-tight mb-4">
                  Additional Notes
                </h1>
                <div className="w-24 h-1 bg-primary mx-auto"></div>
              </div>

              <div className="space-y-4 lg:space-y-6">
                <div className="space-y-4">
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    Any disputes arising under these Terms will be resolved through binding arbitration
                    administered by the American Arbitration Association (AAA), except where prohibited by
                    law. Both parties waive the right to a jury trial.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    The Willow Path Services are not directed to children under 13. By using the Services, you
                    represent that you are at least 13 years old.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    The Willow Path Privacy Policy is incorporated by reference into these Terms of Service.
                  </p>
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                    Willow Path Co. maintains reasonable administrative, physical, and technical safeguards
                    designed to protect the integrity and confidentiality of data processed through the
                    Services.
                  </p>
                </div>
              </div>
            </div>

            {/* Combined Contact Section */}
            <div className="space-y-4 lg:space-y-6 border-t-2 border-primary pt-12">
              <h2 className="font-bookmania text-3xl lg:text-4xl xl:text-5xl font-medium text-secondary tracking-tight">
                How to Contact Willow Path
              </h2>
              <div className="space-y-4">
                <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80">
                  Willow Path understands that these Terms and Privacy Policy contain a lot of information to
                  read and understand. If you have questions about our Terms of Service, Privacy Policy, or
                  any other aspects of our services, please feel free to reach out to us.
                </p>
                <div className="bg-primary/5 p-6 rounded-lg">
                  <p className="text-lg lg:text-xl xl:text-2xl leading-[140%] tracking-wide text-foreground/80 text-center">
                    <strong>Contact us:</strong>{' '}
                    <a
                      href="mailto:support@willow-path.com"
                      className="text-primary hover:underline font-semibold">
                      support@willow-path.com
                    </a>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
